### Create user
POST http://localhost:3000/api/login/new
content-type: application/json

{
  "nombre": "elon",
  "email": "elon@gmail.com",
  "password": "123123"
}

### Login user
POST http://localhost:3000/api/login
content-type: application/json

{
  "email": "elon@gmail.com",
  "password": "123123"
}

### Renew token
GET http://localhost:3000/api/login/renew
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2Q2ZGE3ODdiOWNmYjg5YzA5NWRlMWYiLCJpYXQiOjE2NzUwMjYwNjIsImV4cCI6MTY3NTExMjQ2Mn0.eT5lDB8wFm7H4c6xtV432w5AwXojLOpupkGVwhP52Z8 

{

}

### Get usuarios
GET http://localhost:3000/api/usuarios
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2RlYWNiMmM0M2IwMzdiNDdkMTEzMWMiLCJpYXQiOjE2NzU4OTg2MTEsImV4cCI6MTY3NTk4NTAxMX0.VP2byooHvpMq0k8M5Gt6nl7RLw34_zhq_7hHJ1pqPBs

{

}

### Get mensajes
GET http://localhost:3000/api/mensajes/63d6d71512f2178ca8387824
content-type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2RlYWNiMmM0M2IwMzdiNDdkMTEzMWMiLCJpYXQiOjE2NzU4OTg2MTEsImV4cCI6MTY3NTk4NTAxMX0.VP2byooHvpMq0k8M5Gt6nl7RLw34_zhq_7hHJ1pqPBs

{

}